name = "Swish"
license = "MIT"
description = "An elegant, dignified theme for a polished reading experience"
homepage = "https://github.com/harrisonturton/swish"
tags = ["blog", "elegant", "minimalistic", "clean", "light"]
features = ["blog"]
min_version = 0.19
paginate = 5

pygmentsCodeFences: true
pygmentsStyle = "monokai"
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true

[author]
  name = "Harrison Turton"
  homepage = "https://github.com/harrisonturton"
